### ISSUE TITLE
Preview recurring bookings - not working

### ISSUE THREAD

**Issue by ozanarabaci** [classroombookings/classroombookings#49]
Preview button is not working. 
If I select "end of session" in the "Until..." section, it works, 
if I choose something else, the button becomes useless.
Is it just me having this problem?

XAMPP installed on Windows
Thank you

**Comment by craigrodway** [comment]
Hi @ozanarabaci, thanks for reporting this.

I've tried to reproduce this problem, and it only seems to occur if the "Until..." date is _before_ the selected "Starting from..." date. The Until date should always be the same as, or after, the Start date.

This doesn't seem to be an issue, but should definitely be picked up by validation and display an appropriate message instead.

**Comment by ozanarabaci** [comment]
Hi @craigrodway, 
I tested the situation, just as you said, there is no problem when the future date is selected.
Notification message may be required to be added.
Thank you for your interest.
