### ISSUE TITLE
Eliminate double bookings problem

### ISSUE THREAD

**Issue by ozanarabaci** [classroombookings/classroombookings#50]
Hi,
I ran into another problem.
Conflict checking is done on a periodic basis only.
If a period is entered in hours that contain each other, it does not see it as a conflict.
It allows me to choose the same instructor and room for periods starting at 09:30 and 10:00.

![image](https://user-images.githubusercontent.com/92164569/203245206-476326bb-ce3a-4baf-a5e4-15e7f5bf653b.png)

![image](https://user-images.githubusercontent.com/92164569/203245976-7c59287f-583a-485d-a217-1d40de90aeb7.png)

**Comment by craigrodway** [comment]
This is currently by design. Periods should be created without any overlap to prevent this from happening.
