### ISSUE TITLE
Cannot connect to database

### ISSUE THREAD

**Issue by AnthonyDownerEEG** [classroombookings/classroombookings#58]
Hello there,

New to the Web App and Web Server scene trying out a bunch of Education Room Booking software and found this one to be very promising!

Gone through the installation instructions plus a few Ytube videos about MYSQL and PHPMyAdmin and keep getting to the installation CRBs screen and then just getting the following error see image.

Currently running in a Win10VM

Do let me know what other logs or files I can provide to help!

Thanks!

![Screenshot 2023-09-19 at 12 49 02](https://github.com/classroombookings/classroombookings/assets/145455958/a481d5a3-36e9-440d-b110-114eab5e6eda)

**Comment by AnthonyDownerEEG** [comment]
Hi @craigrodway 

Thanks for the speedy response! Yes I did note the support thing - I will check out the troubleshooting comments and give a fresh install of the new version etc a go! 

Thanks for replying really appreciate it

**Comment by craigrodway** [comment]
Hi again! No problem. Please use 2.8.6 if you are starting with a fresh install, there was an issue in 2.8.5.

**Comment by schef** [comment]
Hi guys, i have the same issue with v2.8.6:
- i can't connect using the web interface
- i can connect using `mysql`

here are the logs:
```
INFO - 2024-01-12 18:02:11 --> Database Driver Class Initialized
ERROR - 2024-01-12 18:02:11 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused /var/www/html/crbs-core/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 211
ERROR - 2024-01-12 18:02:11 --> Unable to connect to the database
ERROR - 2024-01-12 18:02:11 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused /var/www/html/crbs-core/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 211
ERROR - 2024-01-12 18:02:11 --> Unable to connect to the database
DEBUG - 2024-01-12 18:02:11 --> File loaded: /var/www/html/crbs-core/application/views/partials/submit.php
DEBUG - 2024-01-12 18:02:11 --> File loaded: /var/www/html/crbs-core/application/modules/install/views/config.php
DEBUG - 2024-01-12 18:02:11 --> File loaded: /var/www/html/crbs-core/application/modules/install/views/config_side.php
DEBUG - 2024-01-12 18:02:11 --> File loaded: /var/www/html/crbs-core/application/views/columns.php
DEBUG - 2024-01-12 18:02:11 --> File loaded: /var/www/html/crbs-core/application/views/layout.php
INFO - 2024-01-12 18:02:11 --> Final output sent to browser
DEBUG - 2024-01-12 18:02:11 --> Total execution time: 0.0029
```

Is there anything else i can try?
This works on version v2.6.4.
Thanks

**Comment by schef** [comment]
It was my fault. While i was using docker I was typing 127.0.0.1 instead of my docker container.
