### ISSUE TITLE
2.8.5 Error 500

### ISSUE THREAD

**Issue by colly72** [classroombookings/classroombookings#59]
I've just upgraded to 2.85 but I get a 500 error when trying to access the bookings page.  I've replaced the assets folder, index.php and renamed the application folder and uploaded the crbs-core folder as per the instructions.

**Comment by craigrodway** [comment]
Please follow the [Troubleshooting](https://www.classroombookings.com/docs/self-hosted/troubleshooting/) steps to help identify where this type of error comes from.

**Comment by colly72** [comment]
I'm getting these errors in the logs:

ERROR - 2023-09-19 15:58:35 --> Severity: Warning --> include(/home/udv6qvky03ay/public_html/crbs-core/vendor/composer/../../crbs-core/application/components/bookings/Context.php): failed to open stream: No such file or directory /home/udv6qvky03ay/public_html/crbs-core/vendor/composer/ClassLoader.php 576
ERROR - 2023-09-19 15:58:35 --> Severity: Warning --> include(): Failed opening '/home/udv6qvky03ay/public_html/crbs-core/vendor/composer/../../crbs-core/application/components/bookings/Context.php' for inclusion (include_path='.:/opt/alt/php74/usr/share/pear') /home/udv6qvky03ay/public_html/crbs-core/vendor/composer/ClassLoader.php 576
ERROR - 2023-09-19 15:58:35 --> Severity: error --> Exception: Class 'app\components\bookings\Context' not found /home/udv6qvky03ay/public_html/crbs-core/application/controllers/Bookings.php 49

**Comment by craigrodway** [comment]
Thanks for the extra info - very helpful! Sorry about the errors, my fault!

Please obtain version 2.8.6 from GitHub and replace your `crbs-core` directory from the downloaded zip file.

**Comment by colly72** [comment]
> Thanks for the extra info - very helpful! Sorry about the errors, my fault!
> 
> Please obtain version 2.8.6 from GitHub and replace your `crbs-core` directory from the downloaded zip file.

I've done that.  Seems to have resolved the issue but I'm getting css/styling issues:

![classroombookings](https://github.com/classroombookings/classroombookings/assets/6650774/34335f9d-18a2-4b55-aaca-bdff8c74483c)

Looks like it can't find main.css and print.css

**Comment by craigrodway** [comment]
Did you add a `.env` file to help with troubleshooting? If so, please remove this now, or change its contents to `production`.

**Comment by colly72** [comment]
> Did you add a `.env` file to help with troubleshooting? If so, please remove this now, or change its contents to `production`.

Aaah, that's done it!  Works great now, thanks so much.

**Comment by craigrodway** [comment]
Brilliant! Thanks for confirming :) 🙌
