### ISSUE TITLE
Typo in recurring booking...

### ISSUE THREAD

**Issue by mikch06** [classroombookings/classroombookings#61]
https://github.com/classroombookings/classroombookings/blob/e023f7e8b35a6bd4e5eaa12c9dea98aead50d1d1/crbs-core/application/controllers/Weeks.php#L169

If you delete this week, all **reurring** bookings that take place on this week will be permanently deleted.
Shoud mean **recurring** booking.

**Comment by craigrodway** [comment]
Thanks for reporting this @mikch06 and for the fix @StuartHannah-Cutler. It has now been fixed in development and will be included in a future release.
