### ISSUE TITLE
Facing issue while installing the application 

### ISSUE THREAD

**Issue by Mohamednivas** [classroombookings/classroombookings#65]
how to resolve this issue

![image](https://github.com/classroombookings/classroombookings/assets/167208081/ff14e4a1-507f-4f00-ad61-4b2e2913a608)

**Comment by craigrodway** [comment]
Your database is not empty; please follow the documentation.

https://www.classroombookings.com/docs/self-hosted/installation/
> classroombookings needs its own empty database.

GitHub issues is only for reporting bugs, not asking for support.
