### ISSUE TITLE
Printable option.

### ISSUE THREAD

**Issue by KF-ITT** [classroombookings/classroombookings#66]
Hi Craig,
I've been working alongside your Classroom booking system for a few months, trying to see what would work in comparison to our spreadsheets etc.

Would it be possible to have the option to print out each week's bookings, or export to csv?

Regards
Kieran.

**Comment by craigrodway** [comment]
Hi Kieran!

classroombookings is designed to be used as a live online system; as soon as information leaves the system via exporting or printing, it can become out of date very quickly (not to mention that unnecessary printing is bad for the environment). As such, these methods aren't encouraged.

The main bookings page does have a print-optimised view, which might help, but this isn't something that will be developed further.

Exporting to CSV for offline analysis is under consideration.
