### ISSUE TITLE
Feature Request: booking approval

### ISSUE THREAD

**Issue by ccomincini** [classroombookings/classroombookings#67]
Hi, this project is great and really well-made.
We are trying it at our school, and it would be great if there  could be a feature for validating or approving bookings for some rooms:

We have rooms than can be booked by everyone, and rooms that need specific authorisation.
we are thinking on two fields per rooms:
1) flag -> need approval
2) teacher selection -> in case of flag who is the teacher that will approve the booking.

This mean a need of 2 new state for the booking (unapproved, approval-pending)

Any approval could generate a notification to the requester, but this is not a must.
Any booking that need approval, should generate a notification to the approver and this will be a need.

Do you think this will be possible in the near future?

**Comment by craigrodway** [comment]
Hi @ccomincini, thanks for your comment. Booking Approval functionality is on the roadmap, but there are other items that will be developed before this so I wouldn't say "near future".

Craig.
